name: Build & Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 3: Prepare SSH key
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > pass.pem
          chmod 600 pass.pem

      # Step 4: Transfer Docker image to EC2
      - name: Transfer Docker image to EC2
        run: |
          docker save myapp:latest | bzip2 | ssh -i pass.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'bunzip2 | docker load'

      # Step 5: Run Docker container on EC2
      - name: Run Docker container on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 myapp:latest
          EOF
