name: Build & Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image locally in Actions
      - name: Build Docker image
        run: |
          docker build -t myapp:latest my-docker-ec2-deploy/

      # Step 3: Run Docker container on EC2
      - name: Deploy Docker image to EC2
        run: |
          docker save myapp:latest | ssh -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'docker load && docker stop myapp || true && docker rm myapp || true && docker run -d --name myapp -p 80:80 myapp:latest'
